### ISSUE TITLE
Deprecated selector in `atom-dark-minimal-ui\index.less`

### ISSUE THREAD

**Issue by GeorgeWL** [mariosbraho/atom-dark-minimal-ui#1]
In `atom-dark-minimal-ui\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.theme-atom-dark-minimal-ui atom-text-editor[mini] .placeholder-text,
.theme-atom-dark-minimal-ui atom-text-editor[mini]::shadow .placeholder-text` => `.theme-atom-dark-minimal-ui atom-text-editor[mini] .placeholder-text,
.theme-atom-dark-minimal-ui atom-text-editor[mini].editor .placeholder-text`

* `.theme-atom-dark-minimal-ui atom-text-editor[mini] .selection .region,
.theme-atom-dark-minimal-ui atom-text-editor[mini]::shadow .selection .region` => `.theme-atom-dark-minimal-ui atom-text-editor[mini] .selection .region,
.theme-atom-dark-minimal-ui atom-text-editor[mini].editor .selection .region`

* `.theme-atom-dark-minimal-ui .badge,
.theme-atom-dark-minimal-ui .deprecation-cop .deprecation-info:hover,
.theme-atom-dark-minimal-ui .list-group .selected::before,
.theme-atom-dark-minimal-ui .list-group li.selected,
.theme-atom-dark-minimal-ui .list-tree .selected::before,
.theme-atom-dark-minimal-ui .nav-pills > li.active > a,
.theme-atom-dark-minimal-ui .nav-pills > li.active > a:focus,
.theme-atom-dark-minimal-ui .nav-pills > li.active > a:hover,
.theme-atom-dark-minimal-ui .settings-view .config-menu .nav > li.active > a,
.theme-atom-dark-minimal-ui .settings-view .keybinding-panel .is-user,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.background-color-selected:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.button-border-color:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.inset-panel-border-color:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.tab-background-color-active:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.tool-panel-border-color:before,
.theme-atom-dark-minimal-ui .tab-bar .tab.active,
.theme-atom-dark-minimal-ui atom-text-editor[mini] .selection .region,
.theme-atom-dark-minimal-ui atom-text-editor[mini]::shadow .selection .region` => `.theme-atom-dark-minimal-ui .badge,
.theme-atom-dark-minimal-ui .deprecation-cop .deprecation-info:hover,
.theme-atom-dark-minimal-ui .list-group .selected::before,
.theme-atom-dark-minimal-ui .list-group li.selected,
.theme-atom-dark-minimal-ui .list-tree .selected::before,
.theme-atom-dark-minimal-ui .nav-pills > li.active > a,
.theme-atom-dark-minimal-ui .nav-pills > li.active > a:focus,
.theme-atom-dark-minimal-ui .nav-pills > li.active > a:hover,
.theme-atom-dark-minimal-ui .settings-view .config-menu .nav > li.active > a,
.theme-atom-dark-minimal-ui .settings-view .keybinding-panel .is-user,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.background-color-selected:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.button-border-color:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.inset-panel-border-color:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.tab-background-color-active:before,
.theme-atom-dark-minimal-ui .styleguide [data-name="variables"] .is-color.tool-panel-border-color:before,
.theme-atom-dark-minimal-ui .tab-bar .tab.active,
.theme-atom-dark-minimal-ui atom-text-editor[mini] .selection .region,
.theme-atom-dark-minimal-ui atom-text-editor[mini].editor .selection .region`

* `.theme-atom-dark-minimal-ui .scrollbars-visible-always atom-text-editor::-webkit-scrollbar-thumb,
.theme-atom-dark-minimal-ui .scrollbars-visible-always::-webkit-scrollbar-thumb,
.theme-atom-dark-minimal-ui .tooltip .keystroke,
.theme-atom-dark-minimal-ui atom-text-editor atom-text-editor-minimap::shadow .minimap-scroll-indicator,
.theme-atom-dark-minimal-ui atom-text-editor::shadow atom-text-editor-minimap::shadow .minimap-scroll-indicator,
.theme-atom-dark-minimal-ui html atom-text-editor-minimap::shadow .minimap-scroll-indicator` => `.theme-atom-dark-minimal-ui .scrollbars-visible-always atom-text-editor::-webkit-scrollbar-thumb,
.theme-atom-dark-minimal-ui .scrollbars-visible-always::-webkit-scrollbar-thumb,
.theme-atom-dark-minimal-ui .tooltip .keystroke,
.theme-atom-dark-minimal-ui atom-text-editor atom-text-editor-minimap::shadow .minimap-scroll-indicator,
.theme-atom-dark-minimal-ui atom-text-editor.editor atom-text-editor-minimap::shadow .minimap-scroll-indicator,
.theme-atom-dark-minimal-ui html atom-text-editor-minimap::shadow .minimap-scroll-indicator`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by mariosbraho** [comment]
Fix was pushed.
